---
title: "Mini chanllenge 2 - assignment"
description: |
  This report is based on the mini challenge 2 from VAST Challenge 2021.
author:
  - name: Yu Yaxin
    url: {}
date: 08-07-2021
output:
 distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.Overview
## 1.1 Background
This report is based on the mini challenge 2 from [VAST Challenge 2021](https://vast-challenge.github.io/2021/). Here is the background: 

GAStech, an oil-products company from Tethys, is expanding into Kronos - an island country, built good relations with the local government as well.Not only GAStech got considerable profit, but also has an impact on the local natural environment.
At the beginning of 1997,the residents of Elodis agricultural town located near the capital of Kronos began to pay attention to an abnormal increase in the occurrence of illnesses such as cancer and birth defects.And they believe this is related to Gastech's business. The residents set up their own POK (Protectors of Kronos) organization to protect the ecological environment in Kronos and prevent continuous deterioration.

During Gastech's celebration party in 2014, the unexplained disappearance of some employees was suspected to be related to the POK organization. And now we got the employees' credit card and loyalty card transaction data, and also their GPS record, to identify anomalies. Due to this, the purpose of this report is to analyze the consumption behaviors of employees at different times and places, use R Studio to visualize the data, screen the existing suspicious behaviors, match the employees with varies of crads, and draw suggestions and conclusions.

## 1.2 literature review
R Studio was originally developed by Robert Gentleman and Ross Ihaka, an integrated development environment (IDE) for the R language. It is a standalone open source project that integrates many powerful programming tools into an intuitive, easy-to-learn interface. This visualizing analysis is based on R Studio, therefore, will introduce some of the R packages. 

The tidyverse is a language for solving data science challenges with R code, encompasses the repeated tasks at the heart of every data science project:data import, tidying, manipulation, visualization, and programming. Its primary goal is to facilitate a conversation between a human and a computer about data.(Hadley Wickham, Mara Averick,etc,2019)

The tidyverse also provides the ggplot2 (Wickham, 2016) package for visualization. [ggplot2](https://ggplot2.tidyverse.org/) is a system for declaratively creating graphics, based on The Grammar of Graphics (Wilkinson, 2005).Data transformation is supported by the core dplyr (Wickham et al., 2019a) package. [dplyr](https://dplyr.tidyverse.org/)
provides verbs that work with whole data frames, such as mutate() to create new variables,filter() to find observations matching given criteria.  

R can be used for visualization and supports various types of charts. It supports
many applications that can be visualized in a simple and contains most of the
information in the plot.The library ggplot() supports visualization for various formats of data and machine learning models. The other libraries that support visualization in R are ggiraph, digraph, ggVis and so on(K. G. SrinivasaSiddesh G. M.Srinidhi H.,2018).


## 1.3 Dataset introduced
MC2 includes 4 CSV format files and a tourist map of Abila with locations of interest identified.  
-- Car-assignments: includes 45 detailed records of vehicle assignments by employees.  
-- Cc_data: contains 1491 credit and debit card transaction amount records in various of locations.  
-- Loyalty_data: 1393 observations of loyalty card transaction of GAStech's employees.  
-- Gps: records the latitude and longitude by each employees' track.

# 2. Data preperation
## 2.1 Import data 
### 2.1.1 Install R packages 

The first step is to install all the packages we will use in a follow-up study. Here will give brief introduction of some packages.  

We use **Tidyverse** to manipulate and clean original dataset, includes ggplot2(wich is mainly for data visualization), dplyr, tidyr, and purrr. **GGiraph** is to make ggplot interactive with users. **Plotly**'s R graphing library makes interactive, publication-quality graphs.The goal of **patchwork** package is to make it ridiculously simple to combine separate ggplots into the same graphic. **visNetwork** is an R package for network visualization. **lubridate** can help to make up for R Studio's lack of processing time data and makes it much easier. The aim of **magrittr** is to decrease development time and improve readability and maintainability of code. With the **tmap** package, thematic maps can be generated with great flexibility. The **raster** package provides classes and functions to manipulate geographic data in ’raster’ format. **igraph** is a collection of libraries for creating and manipulating graphs and analyzing networks.

